Organizations:
  - &OrdererOrg
    Name: OrderingService
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/panha-network.com/msp
    Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
            - orderer.panha-network.com:7050
            
  - &Panha1
    Name: Panha1MSP
    ID: Panha1MSP
    MSPDir: crypto-config/peerOrganizations/be1.panha-network.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('Panha1MSP.admin', 'Panha1MSP.peer', 'Panha1MSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('Panha1MSP.admin', 'Panha1MSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('Panha1MSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('Panha1MSP.peer')"     
    AnchorPeers:
      - Host: peer0.be1.panha-network.com
        Port: 7051

  - &Panha2
    Name: Panha2MSP
    ID: Panha2MSP
    MSPDir: crypto-config/peerOrganizations/be2.panha-network.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('Panha2MSP.admin', 'Panha2MSP.peer', 'Panha2MSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('Panha2MSP.admin', 'Panha2MSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('Panha2MSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('Panha2MSP.peer')" 
    AnchorPeers:
      - Host: peer0.be2.panha-network.com
        Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true
# Orderer

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses: 
        - orderer.panha-network.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers: 
            - 127.0.0.1:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities
# Application

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Profiles:
    OrdererGenesis:
      <<: *ChannelDefaults
      Capabilities:
        <<: *ChannelCapabilities
      Orderer:
        <<: *OrdererDefaults
        Organizations:
          - *OrdererOrg


          
        Capabilities:
          <<: *OrdererCapabilities
      Consortiums:
        MyFirstConsortium:
          Organizations:
            - *Panha1 
            - *Panha2      
    ChannelDemo:
      Consortium: MyFirstConsortium
      <<: *ChannelDefaults
      Application:
        <<: *ApplicationDefaults
        Organizations:
          - *Panha1
          - *Panha2
        Capabilities:
          <<: *ApplicationCapabilities